/**
 * Baked book descriptions (generated by `npm run fetch-descriptions`).
 */
import libraryDescriptionsData from "../data/library-descriptions.json";
import { getLibrary } from "./libraryStore";

const libraryDescriptions = libraryDescriptionsData as Record<string, string>;

export function getLibraryDescription(bookKey: string): string | null {
  const baked = libraryDescriptions[bookKey];
  if (baked) return baked;
  const synced = getLibrary().find((b) => b.key === bookKey)?.description;
  return synced ?? null;
}

export function allLibraryDescriptionEntries(): Record<string, string> {
  return libraryDescriptions;
}
