/**
 * Baked cover URLs for library books (generated by `npm run fetch-covers`).
 * Lets the Want to Read shelf render instantly without waiting on 45 API races.
 */
import libraryCoversData from "../data/library-covers.json";

const libraryCovers = libraryCoversData as Record<string, string>;

export function getLibraryCoverUrl(bookKey: string): string | null {
  return libraryCovers[bookKey] ?? null;
}

export function allLibraryCoverEntries(): Record<string, string> {
  return libraryCovers;
}
